### ISSUE TITLE
toggl-tracker setup no longer works

### ISSUE THREAD

**Issue by xpepper** [danielefongo/toggl-tracker#10]
From a fresh installation:

```
❯ ~ npm install -g toggl-tracker
/Users/pierodibello/.nvm/versions/node/v12.14.0/bin/toggl-tracker -> /Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js
+ toggl-tracker@0.4.4
added 43 packages from 45 contributors in 12.16s

❯ ~ [13s] toggl-tracker config
### No configuration found. Force setup ###

(node:20818) UnhandledPromiseRejectionWarning: Error: Cannot find module './config.json'
Require stack:
- /Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js:57:68
    at step (/Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js:34:23)
    at Object.next (/Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js:15:53)
    at /Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/pierodibello/.nvm/versions/node/v12.14.0/lib/node_modules/toggl-tracker/dist/bin.js:5:12)
(node:20818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

npm version is 6.13.7

**Comment by danielefongo** [comment]
Thanks for reporting the bug. 

The new released version `0.4.5` fixes the problem.
